version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - JAWSDB_URL=${JAWSDB_URL}
      - SESSION_SECRET=${SESSION_SECRET}
    networks:
      - app-network

networks:
  app-network:
